### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by zipkid** [velaluqa/puppet-redmine#5]
Hello,

Can you tell me if there are plans to maintain/update this project and the related puppet-puma ?

Kind regards,

Stefan Goethals.

**Comment by leoc** [comment]
Currently we are pondering the thought of switching to Docker based puppet-modules. This would take a lot of time, though. 

We are still using the current modules and would love to keep them alive, but currently there is not much time at our hands.
We would welcome all pull requests. :+1:
